
development:
  adapter: mysql2
  database: rml_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: rml_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: rml_production
  username: root
  password: 
  encoding: utf8

